// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EdusisDBContext))]
    partial class EdusisDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Curriculas.Curricula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("diseno_curricular_id");

                    b.Property<Guid>("CursoID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("curso_id");

                    b.HasKey("Id");

                    b.HasIndex("CursoID");

                    b.ToTable("diseno_curricular", (string)null);
                });

            modelBuilder.Entity("Domain.Curriculas.Materias.CargosDocentes.SituacionRevista", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("situacion_revista_id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cargo");

                    b.Property<Guid>("DocenteID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("docente_id");

                    b.Property<bool>("EnFunciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("en_funciones");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("MateriaID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("materia_id");

                    b.HasKey("Id")
                        .HasName("PK_SITUACION-REVISTA");

                    b.HasIndex("DocenteID");

                    b.HasIndex("MateriaID");

                    b.ToTable("situacion_revista", (string)null);
                });

            modelBuilder.Entity("Domain.Curriculas.Materias.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("materia_id");

                    b.Property<Guid>("CurriculaID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("diseno_curricular_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<byte>("HorasCatedra")
                        .HasColumnType("tinyint")
                        .HasColumnName("horas_catedra");

                    b.HasKey("Id")
                        .HasName("PK_MATERIA");

                    b.HasIndex("CurriculaID");

                    b.ToTable("materia", (string)null);
                });

            modelBuilder.Entity("Domain.Cursantes.CicloLectivo", b =>
                {
                    b.Property<int>("ciclo_lectivo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ciclo_lectivo_id"));

                    b.Property<int>("Periodo")
                        .HasMaxLength(4)
                        .HasColumnType("smallint")
                        .HasColumnName("periodo");

                    b.HasKey("ciclo_lectivo_id")
                        .HasName("PK_CICLO-LECTIVO");

                    b.ToTable("ciclo_lectivo", (string)null);
                });

            modelBuilder.Entity("Domain.Cursantes.Cursante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cursante_id");

                    b.Property<Guid>("AlumnoID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("alumno_id");

                    b.Property<bool>("EsRecursante")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("ciclo_lectivo_id")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_CURSANTES");

                    b.HasIndex("AlumnoID")
                        .IsUnique();

                    b.HasIndex("ciclo_lectivo_id");

                    b.ToTable("cursantes", (string)null);
                });

            modelBuilder.Entity("Domain.Cursos.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("curso_id");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grado");

                    b.Property<string>("NivelEducativo")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("nivel_educativo");

                    b.HasKey("Id")
                        .HasName("PK_CURSO");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("Domain.Docentes.Puestos.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("puesto_id");

                    b.Property<Guid>("DocenteID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("docente_id");

                    b.Property<bool>("EsEventual")
                        .HasColumnType("bit")
                        .HasColumnName("es_eventual");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("estado");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("posicion");

                    b.HasKey("Id")
                        .HasName("PK_PUESTO");

                    b.HasIndex("DocenteID");

                    b.ToTable("puesto", (string)null);
                });

            modelBuilder.Entity("Domain.Licencias.Licencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("licencia_id");

                    b.Property<Guid>("DocenteID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("docente_id");

                    b.Property<string>("Articulo")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("articulo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("estado");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("observacion");

                    b.HasKey("Id", "DocenteID")
                        .HasName("PK_LICENCIA");

                    b.HasIndex("DocenteID");

                    b.ToTable("licencia", (string)null);
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("persona_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("persona", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Usuarios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK_ROL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("DocenteID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("docente_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("PK_USUARIO");

                    b.HasIndex("DocenteID")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("RolesId", "UsuarioId")
                        .HasName("PK_USUARIO-ROL");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("Domain.Alumnos.Alumno", b =>
                {
                    b.HasBaseType("Domain.Personas.Persona");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("legajo");

                    b.ToTable("alumno", (string)null);
                });

            modelBuilder.Entity("Domain.Docentes.Docente", b =>
                {
                    b.HasBaseType("Domain.Personas.Persona");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("CUIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cuil");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("legajo");

                    b.ToTable("docente", (string)null);
                });

            modelBuilder.Entity("Domain.Curriculas.Curricula", b =>
                {
                    b.HasOne("Domain.Cursos.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CURSO_DISEÑO-CURRICULAR");

                    b.OwnsOne("Domain.Shared.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("CurriculaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("CurriculaId");

                            b1.ToTable("diseno_curricular");

                            b1.WithOwner()
                                .HasForeignKey("CurriculaId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Curriculas.Materias.CargosDocentes.SituacionRevista", b =>
                {
                    b.HasOne("Domain.Docentes.Docente", null)
                        .WithMany()
                        .HasForeignKey("DocenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCENTE_SITUACION-REVISTA");

                    b.HasOne("Domain.Curriculas.Materias.Materia", null)
                        .WithMany("Docentes")
                        .HasForeignKey("MateriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MATERIA_SITUACION-REVISTA");

                    b.OwnsOne("Domain.Shared.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("SituacionRevistaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("SituacionRevistaId");

                            b1.ToTable("situacion_revista");

                            b1.WithOwner()
                                .HasForeignKey("SituacionRevistaId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Curriculas.Materias.Materia", b =>
                {
                    b.HasOne("Domain.Curriculas.Curricula", null)
                        .WithMany("Materias")
                        .HasForeignKey("CurriculaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DISEÑO-CURRICULAR_MATERIA");

                    b.OwnsMany("Domain.Curriculas.Materias.Calificacion", "Calificaciones", b1 =>
                        {
                            b1.Property<Guid>("materia_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("calificacion_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("calificacion_id"));

                            b1.Property<bool>("Asistencia")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("asistencia");

                            b1.Property<Guid>("CursanteID")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("cursante_id");

                            b1.Property<DateTime>("Fecha")
                                .HasColumnType("date")
                                .HasColumnName("fecha");

                            b1.Property<string>("Instancia")
                                .IsRequired()
                                .HasColumnType("varchar(10)")
                                .HasColumnName("instancia");

                            b1.Property<double?>("Nota")
                                .HasColumnType("float(24)")
                                .HasColumnName("nota");

                            b1.Property<string>("Observacion")
                                .HasMaxLength(250)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("observaciones");

                            b1.HasKey("materia_id", "calificacion_id")
                                .HasName("PK_CALIFICACIÓN");

                            b1.HasIndex("CursanteID");

                            b1.ToTable("calificacion", (string)null);

                            b1.HasOne("Domain.Cursantes.Cursante", null)
                                .WithMany()
                                .HasForeignKey("CursanteID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("FK_CURSANTE_CALIFICACIÓN");

                            b1.WithOwner()
                                .HasForeignKey("materia_id")
                                .HasConstraintName("FK_MATERIA_CALIFICACIÓN");
                        });

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("Domain.Cursantes.Cursante", b =>
                {
                    b.HasOne("Domain.Alumnos.Alumno", null)
                        .WithOne()
                        .HasForeignKey("Domain.Cursantes.Cursante", "AlumnoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ALUMNOS_CURSANTES");

                    b.HasOne("Domain.Cursantes.CicloLectivo", "CicloLectivo")
                        .WithMany()
                        .HasForeignKey("ciclo_lectivo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CICLO-LECTIVO_CURSANTES");

                    b.OwnsMany("Domain.Cursantes.Asistencias.Asistencia", "Asistencias", b1 =>
                        {
                            b1.Property<int>("asistencia_id")
                                .HasColumnType("int");

                            b1.Property<Guid>("cursante_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FK_ASISTENCIAS_CURSANTES")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Falta")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Fecha")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan?>("Minutos")
                                .HasColumnType("time");

                            b1.Property<string>("Observacion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("asistencia_id", "cursante_id")
                                .HasName("PK_ASISTENCIAS");

                            b1.HasIndex("FK_ASISTENCIAS_CURSANTES");

                            b1.ToTable("asistencias", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FK_ASISTENCIAS_CURSANTES");
                        });

                    b.Navigation("Asistencias");

                    b.Navigation("CicloLectivo");
                });

            modelBuilder.Entity("Domain.Cursos.Curso", b =>
                {
                    b.OwnsMany("Domain.Cursos.Division", "Divisiones", b1 =>
                        {
                            b1.Property<Guid>("curso_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("division_id");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("char(1)")
                                .HasColumnName("division");

                            b1.Property<Guid?>("Preceptor")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("docente_id");

                            b1.HasKey("curso_id", "Id")
                                .HasName("PK_DIVISION");

                            b1.HasIndex("Preceptor");

                            b1.ToTable("division", (string)null);

                            b1.HasOne("Domain.Docentes.Docente", null)
                                .WithMany()
                                .HasForeignKey("Preceptor")
                                .HasConstraintName("FK_PRECEPTOR_DIVISION");

                            b1.WithOwner()
                                .HasForeignKey("curso_id")
                                .HasConstraintName("FK_CURSO_DIVISION");
                        });

                    b.Navigation("Divisiones");
                });

            modelBuilder.Entity("Domain.Docentes.Puestos.Puesto", b =>
                {
                    b.HasOne("Domain.Docentes.Docente", null)
                        .WithMany("Puestos")
                        .HasForeignKey("DocenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PUESTO_DOCENTE");

                    b.OwnsOne("Domain.Shared.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("PuestoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("PuestoId");

                            b1.ToTable("puesto");

                            b1.WithOwner()
                                .HasForeignKey("PuestoId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Licencias.Licencia", b =>
                {
                    b.HasOne("Domain.Docentes.Docente", null)
                        .WithMany("Licencias")
                        .HasForeignKey("DocenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LICENCIA_DOCENTE");

                    b.OwnsOne("Domain.Shared.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("LicenciaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LicenciaDocenteID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("LicenciaId", "LicenciaDocenteID");

                            b1.ToTable("licencia");

                            b1.WithOwner()
                                .HasForeignKey("LicenciaId", "LicenciaDocenteID");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.OwnsOne("Domain.Personas.DatosPersonales", "DatosPersonales", b1 =>
                        {
                            b1.Property<Guid>("PersonaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("apellido");

                            b1.Property<int>("Documento")
                                .HasMaxLength(50)
                                .HasColumnType("int")
                                .HasColumnName("documento");

                            b1.Property<DateTime>("FechaNacimiento")
                                .HasColumnType("date")
                                .HasColumnName("fecha_nacimiento");

                            b1.Property<string>("Nacionalidad")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("nacionalidad");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("nombre");

                            b1.Property<string>("Sexo")
                                .IsRequired()
                                .HasColumnType("varchar(15)")
                                .HasColumnName("sexo");

                            b1.HasKey("PersonaId");

                            b1.HasIndex("Documento")
                                .IsUnique();

                            b1.ToTable("persona");

                            b1.WithOwner()
                                .HasForeignKey("PersonaId");
                        });

                    b.OwnsOne("Domain.Personas.Domicilios.Domicilio", "Domicilio", b1 =>
                        {
                            b1.Property<Guid>("persona_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("persona_id")
                                .HasName("PK_DOMICILIO");

                            b1.ToTable("domicilio", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("persona_id")
                                .HasConstraintName("FK_PERSONA_DOMICILIO");

                            b1.OwnsOne("Domain.Personas.Domicilios.Direccion", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("Domiciliopersona_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Altura")
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(6)")
                                        .HasColumnName("altura");

                                    b2.Property<string>("Calle")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(50)")
                                        .HasColumnName("calle");

                                    b2.Property<string>("Observacion")
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(120)")
                                        .HasColumnName("observaciones");

                                    b2.Property<string>("Vivienda")
                                        .IsRequired()
                                        .HasColumnType("varchar(20)")
                                        .HasColumnName("vivienda");

                                    b2.HasKey("Domiciliopersona_id");

                                    b2.ToTable("domicilio");

                                    b2.WithOwner()
                                        .HasForeignKey("Domiciliopersona_id");
                                });

                            b1.OwnsOne("Domain.Personas.Domicilios.Ubicacion", "Ubicacion", b2 =>
                                {
                                    b2.Property<Guid>("Domiciliopersona_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Localidad")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(50)")
                                        .HasColumnName("localidad");

                                    b2.Property<string>("Pais")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(50)")
                                        .HasColumnName("pais");

                                    b2.Property<string>("Provincia")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(50)")
                                        .HasColumnName("provincia");

                                    b2.HasKey("Domiciliopersona_id");

                                    b2.ToTable("domicilio");

                                    b2.WithOwner()
                                        .HasForeignKey("Domiciliopersona_id");
                                });

                            b1.Navigation("Direccion")
                                .IsRequired();

                            b1.Navigation("Ubicacion")
                                .IsRequired();
                        });

                    b.Navigation("DatosPersonales")
                        .IsRequired();

                    b.Navigation("Domicilio")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Domain.Docentes.Docente", null)
                        .WithOne()
                        .HasForeignKey("Domain.Usuarios.Usuario", "DocenteID")
                        .HasConstraintName("FK_USUARIO_DOCENTE");
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("Domain.Usuarios.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Alumnos.Alumno", b =>
                {
                    b.HasOne("Domain.Personas.Persona", null)
                        .WithOne()
                        .HasForeignKey("Domain.Alumnos.Alumno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Shared.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("AlumnoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("AlumnoId");

                            b1.ToTable("alumno");

                            b1.WithOwner()
                                .HasForeignKey("AlumnoId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Docentes.Docente", b =>
                {
                    b.HasOne("Domain.Personas.Persona", null)
                        .WithOne()
                        .HasForeignKey("Domain.Docentes.Docente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Shared.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("DocenteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("DocenteId");

                            b1.ToTable("docente");

                            b1.WithOwner()
                                .HasForeignKey("DocenteId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Curriculas.Curricula", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Domain.Curriculas.Materias.Materia", b =>
                {
                    b.Navigation("Docentes");
                });

            modelBuilder.Entity("Domain.Docentes.Docente", b =>
                {
                    b.Navigation("Licencias");

                    b.Navigation("Puestos");
                });
#pragma warning restore 612, 618
        }
    }
}
